version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: valhalla-db-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=valhalla-user
      - POSTGRES_PASSWORD=admin
    volumes:
      - local-pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=dronstarand1@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local-pgdata:
  pgadmin-data:
    
    
    