version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: valhalla-db-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=valhalla-user
      - POSTGRES_PASSWORD=admin
    volumes:
      - local-pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=dronstarand1@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  redis-cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis-cache:/data
    networks:
      - redis-network
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis-cache
      REDIS_HOST: redis-cache
      REDIS_PORT: redis-cache:6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      HTTP_USER: admin
      HTTP_PASSWORD: admin
    ports:
      - 8081:8081
    networks:
      - redis-network

volumes:
  local-pgdata:
  pgadmin-data:
  redis-cache:
    driver: local

networks:
  redis-network:
    driver: bridge
    
    