logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      timeout: 10000
