spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/valhalla-db
    username: valhalla-user
    password: admin
  jpa:
    #hibernate.ddl-auto=<create | create-drop | update | validate | none>
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db.changelog-master.xml
    user: valhalla-user
    password: admin

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
